class PipelineStatus:

    QUEUED = "QUEUED"

    SUCCESS = "SUCCESS"

    FAILED = "FAILED"

    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

    PENDING = "PENDING"

    RUNNING = "RUNNING"

    WAITING_FOR_INPUT = "WAITING_FOR_INPUT"

    SKIPPED = "SKIPPED"

    CANCELLED = "CANCELLED"

    TIMED_OUT = "TIMED_OUT"
