class PipelineStatus:

    QUEUED = "QUEUED"

    SUCCESS = "SUCCESS"

    FAILED = "FAILED"

    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

    PENDING = "PENDING"

    RUNNING = "RUNNING"

    WAITING_FOR_INPUT = "WAITING_FOR_INPUT"

    INPUT_READY = "INPUT_READY"

    BRIEF_GENERATING = "BRIEF_GENERATING"

    READY_FOR_CONTENT = "READY_FOR_CONTENT"

    SKIPPED = "SKIPPED"

    CANCELLED = "CANCELLED"

    TIMED_OUT = "TIMED_OUT"
