import React, { FormEvent, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, ApiError } from "./api";
import "./styles.css";
import "./product.css";
import "./ux.css";
import "./company.css";
import "./intelligence.css";
import { HomePage } from "./components/HomePage";

type Company={workspace_id:string;name:string};
type Stage={status:string;safe_error?:string;started_at?:string;completed_at?:string};
type Artifact={artifact_id?:string;artifact_type?:string;filename?:string};
type Job={product_id:string;status:string;progress:number;current_stage:string;stages:Record<string,Stage>;artifacts:Artifact[];results:Record<string,unknown>};
type Connection={component:string;status:string;channel_title?:string;safe_error?:string};
type ResearchReport={report_id:string;status:string;executive_summary:string;source_ids:string[];confidence:{confidence_level:string;source_count:number;source_quality:string;source_freshness:string;source_agreement:string;coverage:string;uncertainty_notes:string[]};limitations:string[]};
type Meeting={meeting_id:string;status:string;purpose:string;research_report_id:string};
const COMPANY_KEY="aicompany.last-company-id";
const pageNames=["홈","새 작업","작업","결과","인텔리전스","연결"];
const stages=["PLANNING","MUSIC","IMAGE","BLOG","VIDEO","YOUTUBE","NAVER"];
const stageName:Record<string,string>={PLANNING:"기획",MUSIC:"음악",IMAGE:"이미지",BLOG:"블로그",VIDEO:"영상",YOUTUBE:"YouTube",NAVER:"네이버"};
const statusName:Record<string,string>={RUNNING:"작업 중",PENDING:"대기 중",COMPLETED:"완료",SUCCESS:"완료",PUBLISHED:"완료",WAITING_FOR_INPUT:"사용자 입력 대기",CONNECTION_REQUIRED:"계정 연결 필요",USER_ACTION_REQUIRED:"사용자 조치 필요",USER_CONFIRM_REQUIRED:"사용자 확인 필요",FAILED:"실패",CONNECTED:"연결됨",NOT_CONFIGURED:"연결 안 됨",AUTHORIZATION_PENDING:"연결 승인 대기",UNAVAILABLE:"확인 불가"};
const label=(value?:string)=>statusName[String(value||"PENDING").toUpperCase()]||"확인 필요";
const safeConnectionError=(value?:string)=>({CLIENT_CONFIGURATION_REQUIRED:"YouTube 연결 설정을 확인해 주세요.",AUTHORIZATION_DENIED:"Google 연결이 취소되었습니다.",AUTHORIZATION_CANCELLED:"Google 연결이 완료되지 않았습니다.",SCOPE_INVALID:"승인 범위를 확인해 주세요.",CHANNEL_VERIFICATION_FAILED:"연결된 채널을 확인하지 못했습니다.",CONNECTION_FAILED:"YouTube 연결에 실패했습니다."}[String(value||"")]||"연결 상태를 다시 확인해 주세요.");

function App(){
 const[token,setToken]=useState("");const[companies,setCompanies]=useState<Company[]>([]);const[company,setCompany]=useState("");const[page,setPage]=useState("홈");
 const[jobs,setJobs]=useState<Job[]>([]);const[selected,setSelected]=useState<Job|null>(null);const[connections,setConnections]=useState<Connection[]>([]);const[state,setState]=useState<"idle"|"loading"|"error"|"forbidden">("idle");const[message,setMessage]=useState("");const[action,setAction]=useState("");const[feedback,setFeedback]=useState("");const[artifactView,setArtifactView]=useState<{name:string;content:string}|null>(null);const shownProgress=useRef(new Map<string,number>());
 const[reports,setReports]=useState<ResearchReport[]>([]);const[meetings,setMeetings]=useState<Meeting[]>([]);const[intelligenceDetail,setIntelligenceDetail]=useState<Record<string,unknown>|null>(null);const[activeMeeting,setActiveMeeting]=useState<Meeting|null>(null);
 const current=companies.find(item=>item.workspace_id===company);
 const normalize=(values:Job[])=>values.map(item=>{const value=Math.max(shownProgress.current.get(item.product_id)||0,Number(item.progress)||0);shownProgress.current.set(item.product_id,value);return{...item,progress:value}});
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setState("loading");try{const auth=await api<{access_token:string}>("/auth/login",undefined,{method:"POST",body:JSON.stringify({email:data.get("email"),password:data.get("password")})});const response=await api<{items:Company[]}>("/workspaces",auth.access_token);const items=response.items||[];const remembered=localStorage.getItem(COMPANY_KEY);const chosen=(remembered&&items.some(item=>item.workspace_id===remembered)?remembered:items[0]?.workspace_id)||"";setToken(auth.access_token);setCompanies(items);setCompany(chosen);if(chosen)localStorage.setItem(COMPANY_KEY,chosen);setState("idle")}catch(error){fail(error,"로그인에 실패했습니다.")}}
 async function refresh(){if(!token||!company)return;try{const[work,links,research,meeting]=await Promise.all([api<{items:Job[]}>(`/workspaces/${company}/product-jobs`,token),api<{items:Connection[]}>(`/workspaces/${company}/connections`,token),api<{items:ResearchReport[]}>(`/workspaces/${company}/intelligence/reports`,token),api<{items:Meeting[]}>(`/workspaces/${company}/intelligence/meetings`,token)]);const scoped=normalize(work.items||[]);setJobs(scoped);setConnections(links.items||[]);setReports(research.items||[]);setMeetings(meeting.items||[]);setSelected(value=>value?scoped.find(item=>item.product_id===value.product_id)||null:null);setState("idle")}catch(error){fail(error,"회사 작업 정보를 불러오지 못했습니다.")}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer)},[token,company]);
 useEffect(()=>{const listener=(event:Event)=>{const planId=(event as CustomEvent<{plan_id:string}>).detail?.plan_id;if(!activeMeeting||!planId)return;void perform("select-plan","실행 계획을 선택했습니다.",async()=>{await api(`/workspaces/${company}/intelligence/meetings/${activeMeeting.meeting_id}/decision`,token,{method:"POST",body:JSON.stringify({plan_id:planId})});await openIntelligence(activeMeeting)})};window.addEventListener("aicompany-select-plan",listener);return()=>window.removeEventListener("aicompany-select-plan",listener)},[activeMeeting,company,token]);
 function switchCompany(value:string){setCompany(value);setJobs([]);setConnections([]);setReports([]);setMeetings([]);setIntelligenceDetail(null);setSelected(null);setFeedback("");shownProgress.current.clear();localStorage.setItem(COMPANY_KEY,value)}
 async function openIntelligence(meeting:Meeting){try{const[minutes,plans,decision,execution]=await Promise.all([api(`/workspaces/${company}/intelligence/meetings/${meeting.meeting_id}/minutes`,token),api(`/workspaces/${company}/intelligence/meetings/${meeting.meeting_id}/plans`,token),api(`/workspaces/${company}/intelligence/meetings/${meeting.meeting_id}/decision`,token).catch(()=>null),api(`/workspaces/${company}/intelligence/meetings/${meeting.meeting_id}/execution-plan`,token).catch(()=>null)]);setActiveMeeting(meeting);setIntelligenceDetail({minutes,plans,decision,execution})}catch(error){fail(error,"회의 상세를 불러오지 못했습니다.")}}
 async function perform(key:string,success:string,operation:()=>Promise<void>){if(action)return;setAction(key);setFeedback("");try{await operation();setFeedback(success);await refresh()}catch(error){fail(error,"요청을 완료하지 못했습니다.")}finally{setAction("")}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const request=String(new FormData(form).get("request")||"").trim();if(!request)return;await perform("create","작업을 시작했습니다.",async()=>{const value=await api<Job>(`/workspaces/${company}/product-jobs`,token,{method:"POST",body:JSON.stringify({request,idempotency_key:crypto.randomUUID()})});setSelected(value);setPage("작업");form.reset()})}
 const retry=(job:Job)=>perform(`retry-${job.product_id}`,"실패한 단계를 다시 시작했습니다.",async()=>{await api(`/workspaces/${company}/product-jobs/${job.product_id}/retry`,token,{method:"POST",body:JSON.stringify({stage:job.current_stage})})});
 const resume=(job:Job)=>perform(`resume-${job.product_id}`,"작업을 계속 진행합니다.",async()=>{await api(`/workspaces/${company}/product-jobs/${job.product_id}/resume`,token,{method:"POST"})});
 const connectYoutube=()=>perform("connect-youtube","브라우저에서 Google 연결을 완료해 주세요.",async()=>{await api(`/workspaces/${company}/connections/youtube`,token,{method:"POST"})});
 const uploadAudio=(job:Job,file:File)=>perform(`audio-${job.product_id}`,"음원을 확인했습니다. 다음 단계를 시작합니다.",async()=>{await api(`/workspaces/${company}/product-jobs/${job.product_id}/audio?filename=${encodeURIComponent(file.name)}`,token,{method:"POST",body:file,headers:{"Content-Type":file.type||"application/octet-stream"}},300000)});
 async function openArtifact(item:Artifact){if(!item.artifact_id)return;try{const value=await api<{content:unknown}>(`/workspaces/${company}/artifacts/${item.artifact_id}/content`,token);setArtifactView({name:item.filename||item.artifact_type||"결과물",content:typeof value.content==="string"?value.content:JSON.stringify(value.content,null,2)})}catch(error){fail(error,"이 결과물은 화면에서 바로 열 수 없습니다.")}}
 function fail(error:unknown,fallback:string){setState(error instanceof ApiError&&error.status===403?"forbidden":"error");setMessage(error instanceof Error?error.message:fallback)}
 if(!token)return <main className="login"><section><p className="eyebrow">PROJECT APEX</p><h1>나의 AI 회사를<br/>한 곳에서.</h1><p className="muted">로그인하여 콘텐츠 작업을 시작하고 확인하세요.</p><form onSubmit={login}><label>이메일<input name="email" type="email" required/></label><label>비밀번호<input name="password" type="password" required/></label><button disabled={state==="loading"}>{state==="loading"?"로그인 중…":"로그인"}</button>{state==="error"&&<p role="alert" className="error">{message}</p>}</form></section></main>;
 return <div className="shell"><aside><div><p className="eyebrow">AICOMPANY</p><h2>Studio</h2><div className="company-pin"><small>현재 회사</small><strong>{current?.name||"선택 필요"}</strong></div></div><nav>{pageNames.map(item=><button className={page===item?"active":""} onClick={()=>setPage(item)} key={item}>{item}</button>)}</nav><button className="logout" onClick={()=>{setToken("");setJobs([])}}>로그아웃</button></aside><main className="content"><header><div><p className="eyebrow">LOCAL PRODUCT MODE · {current?.name}</p><h1>{page}</h1><div className="top-context"><span className="context-chip">회사: {current?.name}</span><span className="context-chip">사용자 조치 {jobs.filter(job=>["WAITING_FOR_INPUT","CONNECTION_REQUIRED","USER_CONFIRM_REQUIRED"].includes(job.status)).length}건</span></div></div><label className="workspace">회사<select aria-label="회사 선택" value={company} onChange={e=>switchCompany(e.target.value)}>{companies.map(item=><option value={item.workspace_id} key={item.workspace_id}>{item.name}</option>)}</select></label></header>{feedback&&<p className="feedback" aria-live="polite">{feedback}</p>}{state==="forbidden"?<State text="이 회사에 접근할 권한이 없습니다."/>:state==="error"?<State text={message}/>:page==="홈"?<HomePage companyName={current?.name||""} jobs={jobs} onOpen={job=>{setSelected(job as Job);setPage("작업")}}/>:page==="새 작업"?<Create company={current?.name||""} onSubmit={create} busy={action==="create"}/>:page==="연결"?<Connections company={current?.name||""} items={connections} connect={connectYoutube} busy={action==="connect-youtube"}/>:page==="결과"?<Results company={current?.name||""} jobs={jobs} select={job=>{setSelected(job);setPage("작업")}}/>:page==="인텔리전스"?<Intelligence company={current?.name||""} reports={reports} meetings={meetings} detail={intelligenceDetail} open={openIntelligence}/>:<Work company={current?.name||""} jobs={jobs} selected={selected} setSelected={setSelected} retry={retry} upload={uploadAudio} resume={resume} open={openArtifact} connections={connections} connect={connectYoutube} action={action}/>}</main>{artifactView&&<dialog open className="artifact-view"><h3>{artifactView.name}</h3><pre>{artifactView.content}</pre><button onClick={()=>setArtifactView(null)}>닫기</button></dialog>}</div>
}

function Intelligence({company,reports,meetings,detail,open}:{company:string;reports:ResearchReport[];meetings:Meeting[];detail:Record<string,unknown>|null;open:(meeting:Meeting)=>void}){
 const plans=((detail?.plans as {items?:Array<{plan_id:string;title:string;concept:string;risks:string[]}>}|undefined)?.items)||[];
 return <section className="panel intelligence"><p className="scope-note">현재 회사 <strong>{company}</strong>의 근거·회의·결정 기록입니다.</p><h3>Research Report</h3>{reports.length?reports.map(report=><article key={report.report_id}><strong>{label(report.status)}</strong><p>{report.executive_summary}</p><small>출처 {report.source_ids.length}개 · 신뢰 수준 {report.confidence.confidence_level}</small><p>근거: 품질 {report.confidence.source_quality}, 최신성 {report.confidence.source_freshness}, 일치 {report.confidence.source_agreement}, 범위 {report.confidence.coverage}</p><ul>{report.limitations.map(value=><li key={value}>{value}</li>)}</ul></article>):<p className="muted">조사 보고서가 없습니다.</p>}<h3>Meeting / Plan / Decision</h3>{meetings.map(meeting=><button className="result-row" key={meeting.meeting_id} onClick={()=>open(meeting)}><span>{meeting.purpose}</span><b>{label(meeting.status)}</b></button>)}{plans.length>0&&<div className="plan-compare">{plans.map(plan=><article key={plan.plan_id}><strong>{plan.title}</strong><p>{plan.concept}</p><small>{plan.risks.join(", ")}</small><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent("aicompany-select-plan",{detail:{plan_id:plan.plan_id}}))}>이 계획 선택</button></article>)}</div>}{detail&&<pre className="intelligence-detail">{JSON.stringify(detail,null,2)}</pre>}</section>
}

function Create({company,onSubmit,busy}:{company:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <section className="composer"><p className="eyebrow">{company} · 새 작업</p><h2>AICompany에 무엇을 맡길까요?</h2><form onSubmit={onSubmit}><textarea name="request" rows={6} maxLength={4000} required placeholder="감성 피아노곡을 만들고 콘텐츠 게시까지 준비해 줘."/><button disabled={busy}>{busy?"작업 생성 중…":"작업 시작"}</button></form></section>}
function Work({company,jobs,selected,setSelected,retry,upload,resume,open,connections,connect,action}:{company:string;jobs:Job[];selected:Job|null;setSelected:(job:Job)=>void;retry:(job:Job)=>void;upload:(job:Job,file:File)=>void;resume:(job:Job)=>void;open:(item:Artifact)=>void;connections:Connection[];connect:()=>void;action:string}){const job=selected||jobs[0];const youtube=connections.find(item=>item.component==="youtube");return <><p className="scope-note">현재 회사 <strong>{company}</strong>의 작업입니다.</p><section className="job-list"><h3>작업 목록</h3>{jobs.length?jobs.map(item=><button key={item.product_id} onClick={()=>setSelected(item)}><span>{stageName[item.current_stage]}</span><b>{label(item.status)}</b></button>):<p className="muted">이 회사에서 시작한 작업이 없습니다.</p>}</section>{job&&<section className="workflow"><div className={`progress ${job.status==="RUNNING"?"indeterminate":""}`} aria-label={`진행률 ${job.progress}%`}><span style={{width:`${job.progress}%`}}/></div><p className="workflow-state">{job.status==="RUNNING"&&<span className="spinner"/>}<strong>{label(job.status)}</strong> · {job.progress}%</p><p>{guidance(job,company)}</p><div className="stage-grid">{stages.map(name=>{const value=job.stages[name]?.status||"PENDING";return <article key={name} className={value.toLowerCase()}><small>{stageName[name]}</small><strong>{label(value)}</strong>{value==="RUNNING"&&<span className="spinner"/>}</article>})}</div>{job.status==="FAILED"&&<button disabled={!!action} onClick={()=>retry(job)}>{action?"다시 시작 중…":`${stageName[job.current_stage]} 다시 실행`}</button>}{job.status==="WAITING_FOR_INPUT"&&job.current_stage==="PLANNING"&&<section className="checkpoint"><h3>완성된 음원이 필요합니다</h3><p>Suno 제작 패키지를 확인한 후 이 회사에 음원을 업로드해 주세요.</p><ArtifactList items={job.artifacts} open={open} planningOnly/><input aria-label="완성 음원" disabled={!!action} type="file" accept=".mp3,.wav,.flac,.m4a,audio/*" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(job,file)}}/></section>}{job.status==="CONNECTION_REQUIRED"&&job.current_stage==="YOUTUBE"&&<section className="checkpoint"><h3>YouTube 연결이 필요합니다</h3><p>연결 대상 회사: <strong>{company}</strong></p>{youtube?.status==="CONNECTED"?<button disabled={!!action} onClick={()=>resume(job)}>{action?"계속 진행 중…":"작업 계속하기"}</button>:<button disabled={!!action||youtube?.status==="AUTHORIZATION_PENDING"} onClick={connect}>{youtube?.status==="AUTHORIZATION_PENDING"?"Google 승인 대기 중…":"YouTube 연결하기"}</button>}{youtube?.status==="FAILED"&&<p role="alert" className="error">{safeConnectionError(youtube.safe_error)}</p>}</section>}{["USER_ACTION_REQUIRED","USER_CONFIRM_REQUIRED"].includes(job.status)&&<section className="checkpoint"><p>{job.current_stage==="NAVER"?"네이버 브라우저에서 내용을 확인하고 게시 버튼을 직접 눌러 주세요.":"안내된 사용자 조치를 완료해 주세요."}</p><button disabled={!!action} onClick={()=>resume(job)}>{action?"확인 중…":job.current_stage==="NAVER"?"네이버 게시 준비 열기":"완료 여부 확인"}</button></section>}<Activity job={job}/><ResultDetail job={job} open={open}/></section>}</>}
function guidance(job:Job,company:string){const stage=stageName[job.current_stage]||"현재";if(job.status==="RUNNING")return `${stage} 작업을 처리하고 있습니다. 실제 이벤트가 기록되면 상태가 갱신됩니다.`;if(job.status==="WAITING_FOR_INPUT")return `${company} 작업에 완성된 음원을 업로드해 주세요.`;if(job.status==="CONNECTION_REQUIRED")return `${company}의 ${stage} 계정을 연결해야 다음 단계로 진행할 수 있습니다.`;if(job.status==="USER_CONFIRM_REQUIRED")return `${stage}에서 사용자의 최종 확인을 기다리고 있습니다.`;if(job.status==="FAILED")return `${stage} 단계가 안전하게 중지되었습니다. 해당 단계만 다시 실행할 수 있습니다.`;if(job.status==="COMPLETED")return "모든 단계가 완료되었습니다. 결과 화면에서 확인하세요.";return `${stage} 단계가 실행을 기다리고 있습니다.`}
function Activity({job}:{job:Job}){const items=stages.flatMap(name=>{const value=job.stages[name];const at=value?.completed_at||value?.started_at;return at?[{name,at,status:value.status}]:[]}).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,5);return <section className="activity"><h3>최근 활동</h3>{items.length?<ul>{items.map((item,index)=><li key={`${item.name}-${index}`}><strong>{stageName[item.name]}</strong> {label(item.status)} <time>{new Date(item.at).toLocaleString("ko-KR")}</time></li>)}</ul>:<p className="muted">아직 기록된 활동이 없습니다.</p>}</section>}
function Results({company,jobs,select}:{company:string;jobs:Job[];select:(job:Job)=>void}){return <section className="panel"><p className="scope-note">현재 회사 <strong>{company}</strong>의 결과입니다.</p><h3>작업 결과</h3>{jobs.filter(job=>Object.keys(job.results||{}).length||job.artifacts?.length).map(job=><button className="result-row" key={job.product_id} onClick={()=>select(job)}><span>{stageName[job.current_stage]||"프로젝트"}</span><b>결과물 {job.artifacts?.length||0}개</b></button>)}</section>}
function ResultDetail({job,open}:{job:Job;open:(item:Artifact)=>void}){return <section className="panel results"><h3>결과</h3><div className="result-grid">{["music","image","blog","video","youtube","naver"].map(kind=>{const value=job.results?.[kind] as {published_url?:unknown}|undefined;const url=typeof value?.published_url==="string"&&/^https:\/\/(www\.youtube\.com|blog\.naver\.com)\//.test(value.published_url)?value.published_url:null;return <article key={kind}><small>{kind}</small><strong>{value?"사용 가능":"대기 중"}</strong>{url&&<a href={url} target="_blank" rel="noreferrer">결과 열기</a>}</article>})}</div><ArtifactList items={job.artifacts} open={open}/><p className="muted">안전한 이름과 메타데이터만 표시되며 내부 경로는 숨겨집니다.</p></section>}
function ArtifactList({items,open,planningOnly=false}:{items:Artifact[];open:(item:Artifact)=>void;planningOnly?:boolean}){const filtered=(items||[]).filter((item,index,all)=>item.artifact_id&&all.findIndex(value=>value.artifact_id===item.artifact_id)===index).filter(item=>!planningOnly||["MUSIC_PLAN","SUNO_PACKAGE","TEXT","JSON"].includes(item.artifact_type||""));return filtered.length?<div className="artifact-list">{filtered.map(item=><button key={item.artifact_id} onClick={()=>open(item)}><span>{item.filename||item.artifact_type||"결과물"}</span><small>안전한 내용 보기</small></button>)}</div>:null}
function Connections({company,items,connect,busy}:{company:string;items:Connection[];connect:()=>void;busy:boolean}){return <><p className="scope-note">현재 회사 <strong>{company}</strong>의 연결입니다. 다른 회사의 연결은 사용되지 않습니다.</p><section className="connection-grid">{items.map(item=><article key={item.component}><span className={`dot ${item.status.toLowerCase()}`}/><div><h3>{item.component==="youtube"?"YouTube":item.component}</h3><p>{label(item.status)}</p>{item.channel_title&&<p className="muted">{item.channel_title}</p>}{item.component==="youtube"&&!["CONNECTED","AUTHORIZATION_PENDING"].includes(item.status)&&<button disabled={busy} onClick={connect}>{busy?"연결 시작 중…":"YouTube 연결하기"}</button>}{item.component==="youtube"&&item.status==="AUTHORIZATION_PENDING"&&<p><span className="spinner"/> 브라우저에서 승인해 주세요.</p>}{item.safe_error&&item.status==="FAILED"&&<p role="alert" className="error">{safeConnectionError(item.safe_error)}</p>}</div></article>)}</section></>}
function State({text}:{text:string}){return <section className="state" role="status">{text}</section>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
