import React,{useState} from "react";
import {api} from "../api";
type Brief={production_brief_id:string;concept:string};
type Candidate={candidate_id:string;variant_index:number;concept_variant:string;text_direction:string;visual_direction:string;platform_strategy:string};
type Report={approval_status:string;selected_candidate_id?:string;scores:Array<{candidate_id:string;total_score:number;passed:boolean}>;improvement_count:number;limitations:string[]};
export function ProductionQualityPanel({workspaceId,token,briefs}:{workspaceId:string;token:string;briefs:Brief[]}){
 const[candidates,setCandidates]=useState<Candidate[]>([]),[comparison,setComparison]=useState(""),[report,setReport]=useState<Report|null>(null),[message,setMessage]=useState("");
 async function open(brief:Brief){try{const[c,d,r]=await Promise.all([api<{items:Candidate[]}>(`/workspaces/${workspaceId}/production/briefs/${brief.production_brief_id}/candidates`,token),api<{status:string}>(`/workspaces/${workspaceId}/production/briefs/${brief.production_brief_id}/comparison`,token),api<Report>(`/workspaces/${workspaceId}/quality/briefs/${brief.production_brief_id}/report`,token)]);setCandidates(c.items);setComparison(d.status);setReport(r)}catch{setMessage("품질 정보를 안전하게 불러오지 못했습니다.")}}
 async function select(briefId:string,candidateId:string){try{setReport(await api<Report>(`/workspaces/${workspaceId}/quality/briefs/${briefId}/selection`,token,{method:"POST",body:JSON.stringify({candidate_id:candidateId})}));setMessage("승인 후보를 선택했습니다.")}catch{setMessage("QA 승인 후보만 선택할 수 있습니다.")}}
 const brief=briefs[0];return <section className="panel intelligence"><h3>Production / Quality Intelligence</h3>{briefs.map(value=><button className="result-row" key={value.production_brief_id} onClick={()=>open(value)}><span>{value.concept}</span><b>후보 비교</b></button>)}{comparison&&<p>반복 검사: <strong>{comparison}</strong></p>}<div className="plan-compare">{candidates.map(value=><article key={value.candidate_id}><strong>후보 {value.variant_index}: {value.concept_variant}</strong><p>{value.text_direction}</p><small>{value.visual_direction} · {value.platform_strategy}</small>{brief&&<button onClick={()=>select(brief.production_brief_id,value.candidate_id)}>승인 후보 선택</button>}</article>)}</div>{report&&<article><h3>Final Quality Report</h3><p>{report.approval_status} · 개선 {report.improvement_count}회</p>{report.scores.map(value=><p key={value.candidate_id}>{(value.total_score*100).toFixed(1)}% · {value.passed?"통과":"기준 미달"}</p>)}<small>{report.limitations.join(" ")}</small></article>}{message&&<p role="status">{message}</p>}</section>
}
